/**
 * This file was generated by the JPA Modeler
 */
package entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;


/**
 * @author Alessio Trentin
 */

@Entity
public class Utente {

    @Id
    private String username;

    @Column(unique = true)
    @Basic
    private String email;

    @Basic
    private long passwordHash;

    @Column(unique = true, nullable = false)
    @Basic(optional = false)
    private String salt;

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getPasswordHash() {
        return this.passwordHash;
    }

    public void setPasswordHash(long passwordHash) {
        this.passwordHash = passwordHash;
    }

    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

}